Repository GoogleChrome/devsummit, pull requests merged in 2019-10, with the labels that each got.

#311 update Hotel URLs to prevent redirects
  src/faqs/items/03-logistics/01-hotels.md
Labels: cla: yes

#293 shift header and it's boxed content to adapt at 1024 instead of 1280
  src/_includes/page.css
Labels: cla: yes

#298 FAQ legibility nits
  src/faqs/index.njk
  src/faqs/styles.css
Labels: cla: yes

#299 Further optimize SVGs
  src/_includes/add-to-cal/assets/calendar-icon.svg
  src/_includes/calendar-widget/assets/clock.svg
  src/_includes/footer/assets/email.svg
  src/_includes/footer/assets/fullgoogle.svg
  src/_includes/footer/assets/g.svg
  src/_includes/footer/assets/github.svg
  src/_includes/footer/assets/twitter.svg
  src/_includes/footer/assets/youtube.svg
  src/assets/chromelogo.svg
  src/assets/register-icon.svg
  src/assets/speakers/default.svg
  src/assets/squiggles/1.svg
  src/assets/squiggles/2.svg
  src/assets/squiggles/banner.svg
  src/schedule/assets/coffee.svg
  src/schedule/assets/food.svg
Labels: cla: yes

#315 Panel speakers
  src/_includes/layouts/session/style.css
  src/assets/speakers/alex-russell.jpg
  src/assets/speakers/barb-palser.jpg
  src/assets/speakers/margret-schmidt.jpg
  src/assets/speakers/rick-byers.jpg
  src/sessions/qa-with-chrome-leads.md
  src/speakers/alex-russell.md
  src/speakers/barb-palser.md
  src/speakers/ben-goodger.md
  src/speakers/dion-almaer.md
  src/speakers/jon-krafcik.md
  src/speakers/margret-schmidt.md
  src/speakers/rick-byers.md
Labels: cla: yes

#320 Schedule avatar minor updates
  src/schedule/script/create-schedule.js
  src/schedule/style.css
Labels: cla: yes

#317 More intrinsic session items
  src/schedule/style.css
Labels: cla: yes, enhancement, 💀 design

#326 remove duplicate `conferenceName: 'Chrome Dev Summit 2019',`
  confbox.config.js
Labels: cla: yes

#304 Add missing border to content boxes
  src/_includes/calendar-widget/style.css
  src/_includes/content.css
  src/_includes/faq/style.css
  src/_includes/layouts/session/style.css
  src/_includes/main-intro/style.css
  src/_includes/page.css
  src/schedule/style.css
Labels: cla: no, enhancement, 💀 design

#324 Next launch
  confbox.config.js
  src/_includes/calendar-widget/assets/clock.svg
  src/_includes/calendar-widget/style.css
  src/_includes/colors.css
  src/_includes/content.css
  src/_includes/header/index.njk
  src/_includes/header/style.css
  src/_includes/icon-promo.css
  src/_includes/layouts/session/index.njk
  src/_includes/livestream/index.njk
  src/_includes/main-intro/index.njk
  src/_includes/main-intro/style.css
  src/_includes/module.css
  src/_includes/notify-promo/index.njk
  src/_includes/sessions-promo/index.njk
  src/_includes/subscribe-promo/index.njk
  src/_includes/utils.css
  src/assets/clock-icon.svg
  src/assets/notify-icon-dark-blue.svg
  src/assets/youtube-icon.svg
  src/faqs/index.njk
  src/faqs/items/04-attending/13-multifaith-room.md
  src/faqs/items/04-attending/13-prayer-room.md
  src/index.njk
  src/remote/index.njk
  src/remote/style.css
  src/schedule/index.njk
  src/venue/index.njk
  src/venue/style.css
Labels: cla: yes

#323 Schedule stack
  src/schedule/style.css
Labels: cla: yes, enhancement, 💀 design

#330 Avoid displaying the day name for other timezones
  .eleventy.js
  src/schedule/script/create-schedule.js
  src/schedule/script/index.js
Labels: cla: yes

#329 Add #AskChrome content
  src/schedule/index.njk
Labels: cla: yes

#328 "Protecting users" session updates
  src/sessions/protecting-users-on-a-thriving-web.md
  src/sessions/protecting-users-on-a-working-web.md
Labels: cla: yes

#327 Fixes homepage modules adapting too early
  src/_includes/layouts/media-module/style.css
Labels: cla: yes, enhancement, 💀 design

#321 Expanded footer
  src/_includes/colors.css
  src/_includes/footer/index.njk
  src/_includes/footer/style.css
Labels: cla: yes, enhancement, 💀 design

#334 Make `npm start` and `npm run serve` work for everyone
  package.json
Labels: cla: yes

#333 Increase main navigation link padding
  src/_includes/header/style.css
Labels: cla: yes

#332 triangle notches on schedule items fix
  src/schedule/style.css
Labels: cla: yes

#318 Refined shadows
  src/_includes/calendar-widget/style.css
  src/_includes/colors.css
  src/_includes/content.css
  src/_includes/faq/style.css
  src/_includes/header/style.css
  src/_includes/layouts/main/style.css
  src/_includes/layouts/session/style.css
  src/_includes/page.css
  src/_includes/shadows.css
  src/schedule/style.css
Labels: cla: yes, enhancement, 💀 design

#339 Change Surma's talk title and abstract
  src/sessions/the-main-thread-is-a-bad-place-to-run-your-code.md
  src/sessions/the-main-thread-is-overworked-and-underpaid.md
Labels: cla: yes

#340 Add redirect for old talk URL
  firebase.json
Labels: cla: yes
