Repository GoogleChrome/devsummit, pull requests merged in 2019-11, with the labels that each got.

#341 Speaker badge update
  .eleventy.js
  src/_includes/layouts/session/index.njk
  src/_includes/layouts/session/style.css
  src/speakers/adam-argyle.md
  src/speakers/addy-osmani.md
  src/speakers/alex-russell.md
  src/speakers/anil-sabharwal.md
  src/speakers/barb-palser.md
  src/speakers/chris-wilson.md
  src/speakers/dev-gogate.md
  src/speakers/dion-almaer.md
  src/speakers/eiji-kitamura.md
  src/speakers/elizabeth-sweeny.md
  src/speakers/emily-stark.md
  src/speakers/greg-whitworth.md
  src/speakers/houssein-djirdeh.md
  src/speakers/ingvar-stepanyan.md
  src/speakers/jake-archibald.md
  src/speakers/jon-krafcik.md
  src/speakers/kenji-baheux.md
  src/speakers/margret-schmidt.md
  src/speakers/martin-splitt.md
  src/speakers/michael-kleber.md
  src/speakers/nate-schloss.md
  src/speakers/nicole-sullivan.md
  src/speakers/parisa-tabriz.md
  src/speakers/paul-irish.md
  src/speakers/pj-mclachlan.md
  src/speakers/rick-byers.md
  src/speakers/sam-richard.md
  src/speakers/sam-thorogood.md
  src/speakers/shubhie-panicker.md
  src/speakers/simeon-vincent.md
  src/speakers/surma.md
  src/speakers/thomas-nattestad.md
  src/speakers/una-kravets.md
  src/speakers/yoav-weiss.md
  src/speakers/yusuke-utsunomiya.md
Labels: cla: no, enhancement, 💀 design

#343 Print schedule
  src/schedule/index.njk
  src/schedule/print.css
Labels: cla: yes, 💀 design

#331 Goth mode
  src/_includes/colors.css
  src/_includes/content.css
  src/_includes/faq/index.njk
  src/_includes/faq/style.css
  src/_includes/footer/style.css
  src/_includes/header/style.css
  src/_includes/icon-promo.css
  src/_includes/layouts/main/style.css
  src/_includes/main-intro/style.css
  src/schedule/style.css
  src/venue/style.css
Labels: cla: yes, enhancement, 💀 design

#344 FAQ index
  src/faqs/index.njk
Labels: cla: yes

#345 Show video on session page if we have one.
  src/_includes/layouts/session/index.njk
  src/_includes/layouts/session/style.css
Labels: cla: yes

#347 Live now & next, including livestream
  .eleventy.js
  confbox.config.js
  src/_includes/header/index.njk
  src/_includes/header/style.css
  src/_includes/layouts/media-module/index.njk
  src/_includes/layouts/media-module/style.css
  src/_includes/layouts/session/index.njk
  src/_includes/layouts/session/style.css
  src/_includes/now-n-next/index.njk
  src/_includes/now-n-next/script/index.js
  src/_includes/now-n-next/style.css
  src/_includes/speakers.css
  src/assets/small-youtube-icon.svg
  src/index.njk
Labels: cla: yes

#349 Add Schenectady, USA
  src/remote/index.njk
Labels: cla: yes
